stages:
  preprocess:
    cmd: python src/preprocess.py
    params:
    - preprocess.input
    - preprocess.output
    deps:
    - data/raw/data.csv
    - src/preprocess.py
    outs:
    - data/processed/x_test.csv
    - data/processed/x_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/x_train.csv
    - data/processed/y_train.csv
    - src/train.py
    params:
    - train.max_depth
    - train.model
    - train.n_estimators
    - train.random_state
    - train.x_train
    - train.y_train
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/x_test.csv
    - data/processed/y_test.csv
    - models/model.pkl
    - src/evaluate.py
    params:
    - evaluate.model
    - evaluate.x_test
    - evaluate.y_test
