preprocess:
    input: data/raw/data.csv
    output: data/processed

train:
    x_train: data/processed/x_train.csv
    y_train: data/processed/y_train.csv
    model: models/model.pkl
    random_state: 42
    n_estimators: 100
    max_depth: 5

evaluate:
    x_test: data/processed/x_test.csv
    y_test: data/processed/y_test.csv
    model: models/model.pkl
